version: "3.7"
services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    ports:
      - 13378:80
    volumes:
      - /usr/media/audiobookshelf/audiobooks:/audiobooks
      - /usr/media/audiobookshelf/podcasts:/podcasts
      - /usr/media/misc/audiobookshelf:/config
      - /usr/media/audiobookshelf/metadata:/metadata
