name: booklore

services:
  booklore:
    image: ghcr.io/adityachandelgit/booklore-app:latest
    container_name: booklore
    depends_on:
      - mariadb
    ports:
      - "6060:6060"
    volumes:
      - /usr/media/misc/booklore/data:/app/data
      - /usr/media/books:/books
    environment:
      - MYSQL_ROOT_PASSWORD=put-a-safe-password-here
      - BOOKLORE_DATA_PATH=/app/data
      - BOOKLORE_BOOKS_PATH=/books
      - TZ=Europe/Berlin
    restart: unless-stopped

  mariadb:
    image: lscr.io/linuxserver/mariadb:11.4.5
    container_name: booklore-mariadb
    volumes:
      - /usr/media/misc/booklore/config:/config
    environment:
      - MYSQL_ROOT_PASSWORD=put-a-safe-password-here
      - TZ=Europe/Berlin
    restart: unless-stopped
