name: filebrowser

services:
  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    volumes:
      - /usr/media/storage:/srv
      - /usr/media/misc/filebrowser:/database
      - /usr/media/misc/filebrowser:/config
    user: "${UID}:${GID}"
    ports:
      - 8773:80
    restart: unless-stopped
